Algoritmo "Problema_MediaPonderada"

Var


   x, media, y, b: real
   i, n: inteiro


Inicio


   escreva("Quantos casos voce vai digitar? ")
   leia(n)
   escreval
   
   para i de 1 ate n faca
      Escreval("Digite os tres numeros: ")
      leia(x)
      leia(y)
      leia(b)
      
      media<- ((2*x) + (3*y) + (5*b)) / 10
      
      escreval("Media= ", media:3:1)
   fimpara
   






Fimalgoritmo