Algoritmo "PROBLEMA crescente"

Var


   y,x: inteiro



Inicio

     escreval("Digite dois numeros: ")
     leia(x)
     leia(y)
     
     enquanto X<>y faca
        se x<y entao
           escreval ("crescente")
        senao
           escreval("decrescente")
        fimse
        
        escreval("Digite os outros dois numeros: ")
        leia(x)
        leia(y)
     fimenquanto




Fimalgoritmo
