Algoritmo "problema Glicose"

Var

   medidaGlicose: real




Inicio


   escreva("Digite a medida da glicose: ")
   leia(medidaGlicose)
   
   se (medidaGlicose<=100) entao
      escreva("Classificacao: normal")
   senao
      se medidaGlicose<=140 entao
         escreva("Classificacao: elevado")
      senao
         escreva("Classificacao: diabetes")
      fimse
   fimse




      
   
   
   
   




Fimalgoritmo
