Algoritmo "semnome"





Var


   vet: vetor [0..9] de real
   i, a: inteiro




Inicio


      escreval("quantos numeros voce ira digitar? ")
      leia (i)
      
      para a de 0 ate i-1 faca
           escreval("digite um numero: ")
           leia(vet[a])
      
      
      
      fimpara
      
      
      escreval
      escreval("numeros digitados")

      para a de 0 ate i-1 faca
           escreval(vet[a])
      fimpara






Fimalgoritmo